export const BEGIN_AJAX_CALL = 'BEGIN_AJAX_CALL';
export const AJAX_CALL_ERROR = 'AJAX_CALL_ERROR';

export const CREATE_LOGIN_SUCCESS = 'CREATE_LOGIN_SUCCESS';

export const LOAD_PROFILES_SUCCESS = 'LOAD_PROFILES_SUCCESS';
export const CREATE_PROFILE_SUCCESS = 'CREATE_PROFILE_SUCCESS';
export const UPDATE_PROFILE_SUCCESS = 'UPDATE_PROFILE_SUCCESS';
